### ISSUE TITLE
Xperia m dual

### ISSUE THREAD

**Issue by karthiraja888** [RonGokhale/android_device_sony_nicki#11]
xperia m dual devices sim not working data show no sim card problem when flash ip-Ril.zip

**Comment by RonGokhale** [comment]
flash mi2 ril blobs zip from xda post and make sure you running dual sim baseband.

**Comment by karthiraja888** [comment]
may 25 to june 10 nightly working but when am using vpn its
automatically reboots.. latest nighly are. .data show no sim card...
what is solution for this ussue
