### ISSUE TITLE
Problem when calling

### ISSUE THREAD

**Issue by mauromonti** [RonGokhale/android_device_sony_nicki#4]
Hello. I have a problem when making calls using CM11 on my C1904 (single SIM).

When I make a call the phone signal goes off. Everything else works well (including texts) but I can't make any calls.

Here is a logcat: https://www.mediafire.com/?tl7708eb9f4ylie

Thank you Ron for developing for this device!

**Comment by RonGokhale** [comment]
fix for outgoing calls has been posted in xda thread. search their
