### ISSUE TITLE
issue in extracting vendor blobs

### ISSUE THREAD

**Issue by k2wl** [RonGokhale/android_device_sony_nicki#8]
while extracting proprietary files from  proprietary-files.txt there is error while extracting

lib/hw/camera.msm8960.so:lib/hw/vendor-camera.msm8960.so
lib/hw/lights.msm8960.so:lib/hw/vendor-lights.msm8960.so

which can be corrected if following modification is made to the file

lib/hw/camera.msm8960.so
lib/hw/lights.msm8960.so

**Comment by stellirin** [comment]
![Double Face Palm](http://i.stack.imgur.com/jiFfM.jpg)

**Comment by antdking** [comment]
![wuz0eey](https://f.cloud.github.com/assets/2099618/1988951/0c30a03a-8470-11e3-8dd6-0a8d964ce6e0.jpg)

**Comment by galaxyfreak** [comment]
![triple-facepalm-picard-812](https://f.cloud.github.com/assets/2754168/1988974/51540526-8470-11e3-8430-5478b6328adf.jpg)

**Comment by stellirin** [comment]
![Colouring](http://2.bp.blogspot.com/-hkdlr9agnM0/TgSlUEbPYBI/AAAAAAAABQs/jGGZWCJSAmA/s1600/I_fuckin___love_coloring_by_WhiteSt.jpg)

**Comment by antdking** [comment]
http://www.youtube.com/watch?v=GbTO8-tWc4U

**Comment by stellirin** [comment]
![Colouring](https://i.chzbgr.com/maxW500/1273863936/hF7E81D12/)

**Comment by galaxyfreak** [comment]
Problem?
![45159658](https://f.cloud.github.com/assets/2754168/1988997/b53879dc-8470-11e3-9d77-07ba67b0bae5.jpg)

**Comment by stellirin** [comment]
![Sheep](http://meancheese.com/wp-content/uploads/2010/10/sheep-hurr-durr.jpg)

**Comment by stellirin** [comment]
![Git](http://xkcdsw.com/content/img/1787.jpg)

**Comment by antdking** [comment]
![snake](http://cokehappiness.viralprints.com/previews/29488_71_500_500.png)

**Comment by stellirin** [comment]
![Git](https://i.chzbgr.com/maxW500/5385648640/h492060DE/)

**Comment by galaxyfreak** [comment]
![on the internet nobody knows youre a dog](https://f.cloud.github.com/assets/2754168/1989067/c29aff4a-8471-11e3-984c-8e5137f5b2e8.jpg)

**Comment by stellirin** [comment]
![Git](http://img.wonkette.com/wp-content/uploads/2013/12/derpybear.jpg)

**Comment by galaxyfreak** [comment]
![naughty_memes_im_on_a_boat-s468x363-154962](https://f.cloud.github.com/assets/2754168/1989102/5140c48c-8472-11e3-9b9b-722b0747f4dc.jpg)

**Comment by stellirin** [comment]
![Git](http://www.quickmeme.com/img/f5/f5819bc88b7ecbfaab9e900a71f028d87225406299706f7fb943d9a1f98da077.jpg)

**Comment by antdking** [comment]
![lol](http://2.bp.blogspot.com/_shMz2nssroQ/Se8Vj90VeiI/AAAAAAAAAU4/9dpZRkVDxXA/s400/quiter.jpg)
